name: milestone
description: A study app

version: 1.0.8+9

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^0.9.0
  cupertino_icons: ^0.1.2
  flutter_vector_icons: ^0.1.0
  http: ^0.12.0+1
  shared_preferences: ^0.5.2
  xs_progress_hud: ^1.0.2
  connectivity: ^0.4.3+1
  device_id: ^0.1.3
  intl: ^0.15.8
  image_picker: ^0.6.0+1
  multipart_request: ^0.1.1
  flutter_webview_plugin: ^0.3.4
  chewie: ^0.9.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/man.png
    - assets/images/woman.png
    - assets/images/logo.png
    - assets/images/background.png
    - assets/images/avatar.png
    - assets/images/splash.png
    - assets/images/login_logo.png

  fonts:
    - family: TitilliumWeb-Black
      fonts:
        - asset: assets/fonts/TitilliumWeb-Black.ttf

    - family: TitilliumWeb-Bold
      fonts:
        - asset: assets/fonts/TitilliumWeb-Bold.ttf

    - family: TitilliumWeb-BoldItalic
      fonts:
        - asset: assets/fonts/TitilliumWeb-BoldItalic.ttf

    - family: TitilliumWeb-ExtraLight
      fonts:
        - asset: assets/fonts/TitilliumWeb-ExtraLight.ttf

    - family: TitilliumWeb-ExtraLightItalic
      fonts:
        - asset: assets/fonts/TitilliumWeb-ExtraLightItalic.ttf

    - family: TitilliumWeb-Italic
      fonts:
        - asset: assets/fonts/TitilliumWeb-Italic.ttf

    - family: TitilliumWeb-Light
      fonts:
        - asset: assets/fonts/TitilliumWeb-Light.ttf

    - family: TitilliumWeb-LightItalic
      fonts:
        - asset: assets/fonts/TitilliumWeb-LightItalic.ttf

    - family: TitilliumWeb-Regular
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf

    - family: TitilliumWeb-SemiBold
      fonts:
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf

    - family: TitilliumWeb-SemiBoldItalic
      fonts:
        - asset: assets/fonts/TitilliumWeb-SemiBoldItalic.ttf

    - family: Digital7-Italic
      fonts:
        - asset: assets/fonts/Digital7-Italic.ttf

    - family: Digital7-Mono
      fonts:
        - asset: assets/fonts/Digital7-Mono.ttf

    - family: Digital7-MonoItalic
      fonts:
        - asset: assets/fonts/Digital7-MonoItalic.ttf

    - family: Digital7
      fonts:
        - asset: assets/fonts/Digital7.ttf
